name: Golang CI

on:
  push:
    paths:
      - api/**
      - cmd/**
      - internal/**
      - .github/workflows/build.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Generate
        run: go generate ./...
      - name: Build
        run: go build