name: Golang CI

on:
  push:
    paths:
      - api/**
      - cmd/**
      - internal/**
      - go.mod
      - go.sum
      - .github/workflows/build.yaml

jobs:
  build:
    strategy:
      matrix:
        cfg:
          - os: ubuntu-latest
            name: linux-x86_64
          - os: ubuntu-24.04-arm
            name: linux-arm64
          - os: macos-latest
            name: darwin-arm64
          - os: windows-latest
            name: windows-x86
          - os: windows-latest
            name: windows-x64
      fail-fast: false
    runs-on: ${{ matrix.cfg.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: Nugine/setup-flatc@v1
      - name: Generate
        run: go generate ./...
      - name: Build
        run: go build ./cmd/nanokv
      - uses: actions/upload-artifact@v4
        with:
          name: nanokv-${{ matrix.cfg.name }}
          path: nanokv*