name: Golang CI

on:
  push:
    paths:
      - api/**
      - cmd/**
      - internal/**
      - go.mod
      - go.sum
      - .github/workflows/build.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: Nugine/setup-flatc@v1
      - name: Generate
        run: go generate ./...
      - name: Build
        run: go build ./cmd/nanokv
      - uses: actions/upload-artifact@v4
        with:
          name: nanokv
          path: nanokv